services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - spg4net

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "5173:80"
    environment:
      VITE_API_BASE: http://backend:8000
    depends_on:
      - backend
    networks:
      - spg4net

networks:
  spg4net:
    driver: bridge
